### ISSUE TITLE
Dealing with private constructors

### ISSUE THREAD

**Issue by powerdude** [pmrogala/Buildenator#60]
Hello,

I have a case where I have entities with private constructors and static factory methods.  Would it be possible to allow a builder to provide its own `Build` method like you would handle a `PostBuild` method?

**Comment by progala2** [comment]
Hello

Thanks for the info, I've checked quickly some tests but I don't see this scenario. 
I'll check it in the morning, I recall I implemented probably something like that. If not I'll add it.

Which version do you use?

**Comment by progala2** [comment]
Ok, I can confirm there's no option to replace the Build() method. 
I'll add it ASAP.

For the time being, if you want, you can just add a method like `CustomBuild()` and use it instead of the `Build()` method

**Comment by powerdude** [comment]
Unfortunately that won't help.  The bigger problem is that the generator uses the private constructor when it shouldn't. The suggestion to override the Build is one method, but there may need to be checks to not use private constructors in the generated code.

**Comment by progala2** [comment]
Okey, I got finally what you mean - we cannot use private constructor outside the class 🤦‍♂️😂

For now I will create a simple solution with an option to disable generating default Build() method, and for the future, I may try to create solution where you can provide static method factory name and basing on the parameters it will generate automatically the build method with the factory static method.

**Comment by progala2** [comment]
https://github.com/progala2/Buildenator/pull/61

**Comment by progala2** [comment]
Workaround applied. For more user friendly solution I will create another ticket.

Let me know if the 8.1.1 helps!

**Comment by pmrogala** [comment]
Could you try to clean build, restart VS, and then do the clean build again?
The code generation is sometimes lagging.

If it's still wrong, could you provide some example how do you use it?

**Comment by pmrogala** [comment]
It works for the following scenario:

[Tests/Buildenator.IntegrationTests.SharedEntities/EntityWithPrivateConstructor.cs](https://github.com/pmrogala/Buildenator/blob/main/Tests/Buildenator.IntegrationTests.SharedEntities/EntityWithPrivateConstructor.cs)

https://github.com/pmrogala/Buildenator/blob/main/Tests/Buildenator.IntegrationTests.Source/Builders/EntityWithPrivateConstructorBuilder.cs

I had to write a custom Build() in the builder to compile the code. If there's no Build method it fails with exception that Build method does not exist

**Comment by powerdude** [comment]
still no luck for me.  Can you try creating a new project that references the 8.1.1 package, please?

**Comment by pmrogala** [comment]
I see what's wrong...
I will add the versioning to the comment, good idea, thanks!

**Comment by pmrogala** [comment]
I have no idea what's going on. It's generated as you pasted, but it generates proper error in VS that it's missing the build method.

When I created a new solution and attached the 8.1.1 it doesn't work properly...

Time to debug it step by step again.

**Comment by pmrogala** [comment]
In debugger it looks like that

```

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a source generator named Buildenator (https://github.com/pmrogala/Buildenator)
//     Version 8.1.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Linq;
using Buildenator.Abstraction.Helpers;
using AutoFixture;
using Moq;
using Buildenator.IntegrationTests.SharedEntities;


namespace Buildenator.IntegrationTests.Source.Builders
{
    public partial class EntityWithPrivateConstructorBuilder
    {
        private readonly Buildenator.IntegrationTests.Source.Fixtures.CustomFixture _fixture = new Buildenator.IntegrationTests.Source.Fixtures.CustomFixture();



        public System.Collections.Generic.IEnumerable<Buildenator.IntegrationTests.SharedEntities.EntityWithPrivateConstructor> BuildMany(int count = 3)
        {
            return Enumerable.Range(0, count).Select(_ => Build());
        }




        /// <summary>
        /// You can "override" it by writing the definition in your part of the builder.
        /// </summary>

        public void PostBuild(Buildenator.IntegrationTests.SharedEntities.EntityWithPrivateConstructor buildResult) { }
    }
}
```

WTF

**Comment by pmrogala** [comment]
I don't know how to reproduce it in the repo, but I fixed it.
I filtered _implicitly generated_ constructors (don't confuse with _default instance_ constructor, it's apparently not the same) and it helped. But why it works differently inside this solution than when using as nuget?
It's a mystery. Maybe some weird compilator bug? 😄 

You can check with 8.1.2

**Comment by powerdude** [comment]
thanks, this does work without errors.  I was hoping to still have the various fields outputted so that I could use them in my `Build` method, but I guess that won't be possible if  the code is ignoring the constructor completely.

**Comment by powerdude** [comment]
I spoke too soon.  This doesn't seem to `see` the default constructor anymore.  I have this class:

```
/// <summary>The web content.</summary>
public class Content : IEntity
{
    /// <summary>Gets or sets the content.</summary>
    /// <value>The content.</value>
    public string Content { get; set; } = string.Empty;

    /// <summary>Gets or sets the errors.</summary>
    /// <value>The errors.</value>
    public string? Errors { get; set; }

    /// <summary>Gets or sets the identifier.</summary>
    /// <value>The identifier.</value>
    public string Id { get; set; } = Guid.NewGuid()
        .ToString();
}
```

and it doesn't generate the `Build` anymore.

**Comment by pmrogala** [comment]
AD 1 - yeah, I forgot about this contraint 🤔The only workaround is enable setting up properties by expressions, but it works only when there's a private/protected set. If you have {get;} only constructor may help.
You can enable `generateMethodsForUnreachableProperties = true` 
https://github.com/pmrogala/Buildenator/blob/main/Buildenator.Abstraction/MakeBuilderAttribute.cs

AD 2 - this starts to be frustrating, once again the test in the repo works correctly and it does not work on nuget level :/

**Comment by pmrogala** [comment]
Ad 2 nope it's mistake on my side. That's good actually :)

**Comment by pmrogala** [comment]
AD 2. I know now why I have different results on nuget and in project.
Even in debug mode, compiler is not complaining about errors in the generated code by some reason. I have to explicitly use some builder in very simple unit test.

**Comment by pmrogala** [comment]
AD 2. So, compiler still is happy but Intelisense mark an error - at least something...

**Comment by pmrogala** [comment]
I found a way to test it properly with local nuget approach - my last hope

https://andrewlock.net/creating-a-source-generator-part-3-integration-testing-and-packaging/

**Comment by powerdude** [comment]
No worries and I understand.  :D

**Comment by pmrogala** [comment]
Should be better now

**Comment by pmrogala** [comment]
I'm working now on possibility to pass the factory method name to the MakeBuilder attribute, so it will generate everything itself.
Hard to say on ETA, because I work on it quite adhoc, but maybe next week :)
@powerdude
