### ISSUE TITLE
Better handling of classes with private constructors and static factory methods.

### ISSUE THREAD

**Issue by pmrogala** [pmrogala/Buildenator#62]
- Better Diagnostics
- Possibility to provide static factory method instead of a constructor.

**Comment by pmrogala** [comment]
Added better diagnostics for situations when there's no public constructor #66

**Comment by pmrogala** [comment]
@powerdude it's done, will be shipped with 8.3.0.0

**Comment by powerdude** [comment]
Hey @pmrogala , just upgraded to the latest and thanks for the addition.  I did discover one thing though? If I defined a builder like so:

``` csharp
[MakeBuilder(typeof(Muscle), staticFactoryMethodName:nameof(Thing.Create))]
public partial class ThingBuilder
{

}
```

The source is generated, but then an error is created on `Thing.Create` due to the addition of the static property in the builder that has the same name as the class: `public static ThingBuilder Thing => new ThingBuilder();`  Wasn't this used to be `Default`.  Can it be named something else?

**Comment by pmrogala** [comment]
Hmmm, is this `Thing` in any namespace? Because the usage of Thing.Create is by full name, so it always should look like `Namespace.Thing.Create` but if the Thing isn't in any namespace then the error may occur.

Could you provide me broader example, so I can add it to the tests, If the case is different from what I wrote?

For the time being you can use `defaultStaticCreator: false` for such case

**Comment by powerdude** [comment]
```
namespace Sample.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Buildenator.Abstraction;

public class Thing
{
    private Thing(string id)
    {
        this.Id=id;
    }

    public string Id { get; private set; }

    public static Thing Create(string id)
    {
        return new Thing(id);
    }
}

[MakeBuilder(typeof(Thing), staticFactoryMethodName: nameof(Thing.Create))]
public partial class ThingBuilder
{

}
```

**Comment by pmrogala** [comment]
You can write:

```
[MakeBuilder(typeof(Thing), staticFactoryMethodName: nameof(Domain.Thing.Create))]
public partial class ThingBuilder
{

}
```
And it will work. 
I will think about the static creator, but it's gonna be a breaking change, so I have to think it over

**Comment by powerdude** [comment]
Also, using `defaultStaticCreator: false` didn't help but the other suggestion does.

**Comment by pmrogala** [comment]
Hmm, that's true, so there's something else going on 🤔

**Comment by pmrogala** [comment]
ok, I see, I mixed up the settings. There's no option now to disable this static method in the builder.
I will add option, but for the time being you can just add the prefix with namespace

**Comment by powerdude** [comment]
One other feature request, can you add a conversion operator:

`    public static implicit operator Thing(ThingBuilder builder) => builder.Build();`

I find myself adding this to most of my builders.

**Comment by pmrogala** [comment]
I will add it as a separate thread, great idea, thanks!

**Comment by pmrogala** [comment]
@powerdude it's already implemented 😂
Try: `implicitCast: true`
You can use it also in the global assembly setting, you don't need to apply it to every builder separately
